config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'static#home'
  get 'posts/recent', to: 'posts#recent'

  resources :communities do
    resources :posts do
      member do
        put 'like', to: 'posts#upvote'
      end
    end
  end

  resources :posts do
    resources :comments, shallow: true
  end
  resources :tags
  resources :users, only: [:index, :show, :edit, :update]
  get 'communities/:id/next', to: 'communities#next'
end

app/models/post.rb
class Post < ApplicationRecord
   extend FriendlyId
   friendly_id :title

  acts_as_votable

  scope :recent, -> { order('posts.created_at DESC').limit(10) }

  belongs_to :user
  belongs_to :community

  has_many :comments, dependent: :destroy

  has_many :tags
  accepts_nested_attributes_for :tags, reject_if: :all_blank

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :link, presence: true
  validates :content, length: { minimum: 50 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote]

  def new
    @post = Post.new
  end

  def recent
    @recent_posts = Post.recent
    render :recent
  end

  def show
    respond_to do |format|
      format.html { @post }
      format.json { render json: @post }
    end
    # render json: @post
  end

  def create
    @community = Community.friendly.find(params[:community_id])
    @post = @community.posts.create(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @community, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if current_user.id == @post.user_id
      @post.destroy

      respond_to do |format|
        format.html { redirect_to community_path(@post.community), notice: 'Post was successfully deleted.' }
        format.json { head :no_content }
      end
    end
  end

  def upvote
    @post.upvote_by current_user
    redirect_back fallback_location: root_path
  end

  private
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content, :link, :user_id, :community_id, tag_ids: [], tags_attributes: [:name])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post, url: { controller: "posts", action: "create" } do |f| %>
<%= render partial: 'shared/error_messages', locals: { object: @post } %>
  <div class="field">
    <%= f.text_field :title, placeholder: 'Post Title' %>
  </div>
  <div class="field">
    <%= f.text_field :link, placeholder: 'Post Link' %>
  </div>
  <div class="field">
    <%= f.text_area :content, placeholder: 'Post content' %>
  </div>
  <div class="field">
    <%= f.fields_for :tags, @post.tags.build do |tag_fields| %>
      <%= tag_fields.text_field :name, placeholder: 'Add a Tag' %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<li>
  <h2><%= post.title %></h2>
  <p>submitted <%= time_ago_in_words(post.created_at) %> ago by <%= link_to "#{post.user.show_name}", user_path(post.user), class: "user-tag" %></p>
  <% post.tags.each do |tag| %>
    <h2 class="tags"><%= link_to tag.name, tag_path(tag) %></h2>
  <% end %>
</li>

app/views/posts/new.html.erb
<h1>Write your post</h1>

<%= render 'form' %>
<%= link_to 'Back', :back %>

app/views/posts/recent.html.erb
<h1>Recent Posts</h1>

<section id="list-posts" class="recent">
  <ul>
    <% @recent_posts.each do |post| %>
      <%= link_to community_post_path(post.community, post) do %>
        <%= render partial: 'post', locals: { post: post } %>
      <% end %>
    <% end %>
  </ul>
</section>

app/views/posts/show.html.erb
<p id="nav-button"><%= link_to 'Back', community_path(@post.community) %></p>

<% if  current_user.id == @post.user_id %>
  <p id="nav-button"><%= link_to 'Delete', [@post.community, @post], method: :delete %></p>
<% end %>

<section id="list">
  <h2><%= link_to "#{@post.title}", @post.link, target: :_blank %></h2>
  <p class="description" id="link"><%= link_to "#{@post.link}", @post.link, target: :_blank %></p>
  <h5>Created by <%= link_to "#{@post.user.show_name}", user_path(@post.user), class: "user-tag" %></h5>
  <p class="description"><%= @post.content %></p>

  <%= link_to like_community_post_path(@post), method: :put do %>
   <div class="engagement">
     <%= image_tag("heart") %>
     <p><%= @post.get_upvotes.size %> </p>
   </div>
  <% end %>
  <div class="engagement">
    <%= image_tag("message-square") %>
    <p><%= @post.comments.size %> </p>
  </div>
</section>

<section id="list-posts">
  <ul>
    <% @post.comments.each do |comment| %>
      <li>
        <h6><%= comment.content %></h6>
        <p>submitted <%= time_ago_in_words(comment.created_at) %> ago by <%= link_to "#{comment.user.show_name}", user_path(comment.user), class: "user-tag" %></p>
        <% if  current_user.id == comment.user_id %>
          <p id="comment-delete"><%= link_to 'Delete', comment, method: :delete %></p>
        <% end %>
      </li>
    <% end %>
  </ul>
</section>

<section id="list-posts" class="comments">
  <%= form_for [@post, Comment.new] do |f| %>
    <%= f.text_area :content, placeholder: 'Comment here...' %><br>
    <%= f.hidden_field :post_id, value: @post.id %>
    <%= f.submit "add", data: { disable: true } %>
  <% end %>
</section>