config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'static#home'
  get 'posts/recent', to: 'posts#recent'

  resources :communities do
    resources :posts do
      member do
        put 'like', to: 'posts#upvote'
      end
    end
  end

  resources :posts do
    resources :comments, shallow: true
  end
  resources :tags
  resources :users, only: [:index, :show, :edit, :update]
  get 'communities/:id/next', to: 'communities#next'
end

app/models/community.rb
class Community < ApplicationRecord
  extend FriendlyId
  friendly_id :title

  belongs_to :poster, class_name: 'User', foreign_key: 'user_id'

  has_many :posts, dependent: :destroy
  has_many :posters, through: :posts, source: :user

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :short_description, length: { minimum: 50 }

  def self.by_created_at
    order('created_at DESC')
  end

  def next
    next_community = self.class.where('id > ?', id).first
	  next_community ? next_community : self.class.first
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: [ :show, :edit, :update, :destroy, :next ]

  def index
    @communities = Community.by_created_at
    respond_to do |format|
      format.html { @communities }
      format.json { render json: @communities }
    end
  end

  def show
    respond_to do |format|
      format.html { @community }
      format.json { render json: @community }
    end
  end

  def next
    @next_community = @community.next
    render json: @next_community
  end

  def new
    @community = current_user.communities.build
  end

  def edit
  end

  def create
    @community = current_user.communities.build(community_params)

    respond_to do |format|
      if @community.save
        format.html { redirect_to @community, notice: 'Community was successfully created.' }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to @community, notice: 'Community was successfully updated.' }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if current_user.id == @community.user_id
      @community.destroy

      respond_to do |format|
        format.html { redirect_to communities_url, notice: 'Community was successfully deleted.' }
        format.json { head :no_content }
      end
    end
  end

  private
    def set_community
      @community = Community.friendly.find(params[:id])
    end

    def community_params
      params.require(:community).permit(:title, :short_description)
    end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_community.html.erb
<h2><%= community.title %></h2>
<p class="description"><%= community.short_description %></p>
<p class="time-ago">
created <%= time_ago_in_words(community.created_at) %> ago by <%= link_to "#{community.poster.show_name}", user_path(community.poster), class: "user-tag" %>
<% if  community.poster.flairs.last != nil %>
  <%= link_to "#{community.poster.flairs.last.name}", user_path(community.poster), class: "user-tag" %>
  <%= link_to "#{community.poster.user_flairs.first.experience_level}", user_path(community.poster), class: "user-tag" %>
<% end %>
</p>

app/views/communities/_form.html.erb
<%= form_for @community do |f| %>
<%= render partial: 'shared/error_messages', locals: { object: @community } %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :short_description %><br>
    <%= f.text_area :short_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/communities/edit.html.erb
<h1>Edit your Community</h1>

<%= render 'form' %>
<%= link_to 'Back', communities_path %>

app/views/communities/index.html.erb
<h1>Communities</h1>

<section id="list">
  <ul>
    <% @communities.each do |community| %>
      <%= link_to community do %>
        <li>
          <%= render partial: 'community', locals: { community: community } %>
        </li>
      <% end %>
    <% end %>
    <%= link_to new_community_path do %>
      <div class="add-link">
        <p ><%= image_tag("plus") %>  Community</p>
      </div>
    <% end %>
  </ul>
</section>

app/views/communities/new.html.erb
<h1>Add a Community</h1>

<%= render 'form' %>
<%= link_to 'Back', communities_path %>

app/views/communities/show.html.erb
<p id="nav-button"><%= link_to 'Back', communities_path %></p>
<p id="nav-button"><%= link_to 'Next', community_path(@community.id + 1), data: { id: @community.id }, class: "show_next" %></p>
<p id="nav-button"><%= pluralize(@community.posts.size, 'post') %></p>

<% if  current_user.id == @community.user_id %>
  <p id="nav-button"><%= link_to 'Delete', @community, method: :delete %></p>
  <p id="nav-button"><%= link_to 'Edit', edit_community_path(@community, @post) %></p>
<% end %>

<section id="list">
  <%= render partial: 'community', locals: { community: @community } %>
</section>

<section id="list-posts">
  <ul>
    <% @community.posts.each do |post| %>
      <%= link_to community_post_path(@community, post) do %>
        <li>
          <%= render partial: 'posts/post', locals: { post: post } %>
        </li>
      <% end %>
    <% end %>
    <%= link_to new_community_post_path(@community) do %>
      <div class="add-link">
        <p ><%= image_tag("plus") %>  Post</p>
      </div>
    <% end %>
  </ul>
</section>